### ISSUE TITLE
Decide release/versioning strategy

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2tools#1]
We should decide how to release/version `brian2tools` with respect to `brian2`. My original proposal was to have a linked release strategy, i.e. we'll release a new version of `brian2tools` whenever we release a version of `brian2`. The advantage is that we don't have to check the compatibility across different versions, during the development cycle, `brian2tools` would test against the current development version of `brian2` so at release time it would be guaranteed to work together. Is this reasonable? The main disadvantages of this approach that I can see:
* we can't release `brian2tools` more often than `brian2` (but hopefully we do releases of `brian2` more regularly in the future)
* It would be weird to do a `brian2tools` release without any changes, just because a new `brian2` version is out
* Starting the versions with 2.0 is a bit odd...

Another question is whether this linking would be strictly enforced, i.e. should the dependency of `brian2tools` on `brian2` would use an exact version number?

On the other hand, if we manage to uncouple `brian2tools` from `brian2` internals as much as possible *and* manage to keep API breaks in `brian2` to a minimum, then all of this is maybe not really an issue. We'll just do `brian2tools` releases whenever (and maybe start at a humble `0.1` version or so), and have it always depend on `brian2>X`, where `X` is the latest release.

Any thoughts on this?

**Comment by thesamovar** [comment]
I would prefer the second strategy if we can keep it decoupled like that. How about we start out with that intention and switch to the other strategy in the future if that isn't working out?

**Comment by mstimberg** [comment]
Ok, thinking about it more I don't see much advantage of the tighter coupling. If anything, it is a good exercise for us to not break compatibility -- if a change in Brian 2 breaks brian2tools then it is very likely that it also breaks some users' code!

So let's do a release (say 0.1) shortly after the Brian 2 2.0 release, with a `brian2>=2.0' dependency.

**Comment by mstimberg** [comment]
I think we agreed that going for independent version numbers (and starting with something like 0.1) is the simpler solution. I am therefore closing this issue.
