### ISSUE TITLE
Plotting the synaptic `delay` variable with `brian_plot` fails

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2tools#21]
We only allow plotting synaptic variables and check whether the variable's group is a `Synapses` object. For `delay`, this is no longer the case in recent Brian versions, its group is now the `SynapticPathway`.

First reported on the mailing list: https://groups.google.com/d/msg/brian-development/-bdFXNhb7XE/A2nf7a0EBAAJ

**Comment by cnjackhu** [comment]
I see the same error in plotting. I am using anaconda. I update using `conda install brian2tools` .
Why this error still there? Thanks

error message:

    brian_plot(connections['XeAe'].delay)

  File "/home/hu/anaconda3/envs/py27/lib/python2.7/site-packages/brian2tools/plotting/base.py", line 154, in brian_plot
    '%s' % type(brian_obj))

NotImplementedError: Do not know how to plot object of type <class 'brian2.core.variables.VariableView'>
