### ISSUE TITLE
Use images / adaptive point size for large synapses?

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2tools#3]
At the moment, if you ``brian_plot(S)`` for a large ``Synapses`` you just get a big blue square and you can't see any structure in it. Perhaps we could either have an image rather than scatter plot, or adaptively decide the size of the scatter symbols based on the number of synapses?

**Comment by mstimberg** [comment]
Yes, I agree, for large number of connections the current plot is not useful. On the other hand, an image plot looks odd for few connections, so I think we'll need an adaptive solution as you say. I think for the `plot_synapses` function we could simply have an option (e.g. to switch between scatter plot and image), but for `brian_plot` I'd like to stay with the simple "fire and forget" approach.

The advantage of an adaptive scatter symbol size would be that we would not need an arbitrary threshold, the change in size would be continuous. On the other hand, the scatter marker size stays the same when one changes the size of the total plot which means that a marker that is fine at a certain window size can be totally off at another size. Or is there some elegant way to deal with this?

Another question: what would be the criterion/metric? Potential number of synapses (i.e. `len(source)*len(target)`) or actual synapses? Two big connected groups with very few synapses might still need big markers...

**Comment by thesamovar** [comment]
I had a quick google and couldn't find a way to do adaptive scatter size. People were suggesting adding Circle patches, but I tried this and it gets very slow very quickly.

I think it depends on a few things. If there are few synapses (not relative to the size, but say an upper limit of 10,000 synapses or something - not sure what the exact cutoff should be) then it should be a scatter. If there are more than that, I think it depends on the total size of the groups. An image is fine, but for groups of size N takes O(N^2) to store which could be very large. So we could have an upper limit to the number of pixels in the image, and beyond that we could switch to a density plot maybe? We can use scipy's KDE code to make nice density plots quite efficiently.

Another option is above a certain number of synapses we switch to ``plot(i, j, ',k')``. I tried that for ``i=rand(n)``, ``j=rand(n)`` and it looks pretty good for a range of window sizes for 10,000<n<300,000. So one option would be: scatter for 0<n<10k; plot with ',' symbol for 10k<n<300k; and then either image or density plot depending on dimensions (i.e. we'd have a maximum number of pixels).

Or maybe we should choose between (scatter/plot) versus (image/density) based on the density of synapses (e.g. scatter/plot for less than 10% connectivity, otherwise image/density). We'd also need to add that if the density was low and the number of synapses was high, we'd have to then use a density plot.

One last thought: actually an image looks for a low number of synapses as long as you use ``interpolation='nearest'``. Try:

```
G=NeuronGroup(10,'v:1',threshold='False')
S=Synapses(G,G,on_pre='v+=1')
S.connect(j='i')
W=zeros((len(G),len(G)))
W[S.i,S.j]=1
imshow(W, origin='lower left', interpolation='nearest', cmap='gray_r')
```

to get 

![figure_1](https://cloud.githubusercontent.com/assets/2903870/14725877/69d9b4ac-0816-11e6-9487-76649f4952ba.png)

So another option is we just use image or density plot depending on the number of neurons. We could potentially make an exception and use scatter for a very low number of neurons (say less than 100).

**Comment by mstimberg** [comment]
Just putting this here to not forget about it: maybe matplotlib's `spy` function which works for sparse matrices could be useful? http://matplotlib.org/api/axes_api.html#matplotlib.axes.Axes.spy

**Comment by thesamovar** [comment]
Just tried it on CUBA example and it wasn't terribly good, unfortunately.

**Comment by mstimberg** [comment]
I wonder whether it is really useful to come up with a complex mechanism here... I agree that the image is not bad for low numbers of neurons and I also agree that spy does not help us that much (I did not read the bit where it says that its image plot does not work for sparse matrices...). But then, what *would* be a good visualization of the connectivity in the CUBA example? It is random, so there is no structure to see in the first place. I guess the most general plot for many connections is something like `hexbin` but then I don't really see for what kind of use case this will really be useful. Most interesting connectivities will be something in 2D and plotting this for the matrix of source indices vs. target indices will not be easy to decipher. Maybe it would be useful instead to spend some time on helper functions to visualize 2D connectivities?

**Comment by thesamovar** [comment]
I didn't know about hexbin, that's really nice. My preference would be to do scatter/plot(..,',') for low numbers of synapses (regardless of number of neurons), image when the size of the image isn't too large (i.e. num neurons less than 5k or so) and hexbin otherwise. However, I don't think it's critical to do this, and I think it's more about what you feel like implementing. It's not core Brian and ``brian_plot`` is only for convenience not for publication ready figures, so we shouldn't spend too much effort on it.

True for CUBA it's random, but you might see something for topographic examples, etc.
